name = "dumbbell"
source = "data/dumbbell.msh"
seeds = [1,2,3,4,5,6,7,8,9,10]
alpha = 1.0
kappa = 200.0
nu = 2.5
dimension_factor = 0.5
noise_variance = 0.0005
truncation_level = 500
subset_size = 50
subset_size_ls = 500
subset_size_int = 50
kappa_ls_initial = 0.25
num_data_grid_points = 51
num_data = 1000
num_ls_iters = 1000
num_plot = 1556