name = "sphere"
source = "data/icosphere.obj"
seeds = [1,2,3,4,5,6,7,8,9,10]
alpha = 1.0
kappa = 0.25
nu = 2.5
dimension_factor = 1.0
noise_variance = 0.0005
truncation_level = 500
subset_size = 500
subset_size_ls = 500
subset_size_int = 1000
kappa_ls_initial = 0.25
num_data_grid_points = 41
num_data = 1000
num_ls_iters = 1000
num_plot = 1000